title: Social Graphs and Interactions
logo: circle.jpg
description: Takuya Omori, Esther Zang and Laura Vargas
show_downloads: true
google_analytics:
navbar-links:
  Resources:
    - Explainer notebook: "http://deanattali.com/beautiful-jekyll/"
theme: jekyll-theme-minimal
