title: "Social Graphs and Interactions"
logo: circle.jpg
description: [ExplainerNotebook](https://nbviewer.jupyter.org/github/Miniphant/socialgraphs/blob/master/Final%20Project.ipynb)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
